package owenwang.ems;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Locale;

public class EmployeeDetails extends JPanel {
    private JPanel panel1;
    private JLabel fNameField;
    private JLabel lNameField;
    private JLabel typeField;
    private JLabel genderField;
    private JLabel workLocationField;
    private JButton editButton;
    private JButton removeButton;
    private JLabel employeeName;
    private JLabel employeeNumber;
    private JLabel salaryLabel;
    private JLabel salaryField;
    private JLabel deductionRateField;
    private JLabel hourlyWageLabel;
    private JLabel hourlyWageField;
    private JLabel hoursPerWeekLabel;
    private JLabel hoursPerWeekField;
    private JLabel weeksPerYearLabel;
    private JLabel weeksPerYearField;
    private JLabel grossIncomeField;
    private JLabel netIncomeField;
    private JLabel placeholderLabel;
    private EmployeeInfo employee;

    public void setEmployee(EmployeeInfo emp) {
        employee = emp;
        update();
    }

    public EmployeeInfo getEmployee() {
        return employee;
    }

    public void setPlaceholder(String placeholder) {
        placeholderLabel.setText(placeholder);
    }

    public void addRemovalListener(ActionListener l) {
        removeButton.addActionListener(l);
    }

    public void addEditListener(ActionListener l) {
        editButton.addActionListener(l);
    }

    private void updateVisibility() {
        var e = employee;
        if (e == null) return;
        salaryLabel.setVisible(e instanceof FTE);
        salaryField.setVisible(e instanceof FTE);
        hourlyWageLabel.setVisible(e instanceof PTE);
        hourlyWageField.setVisible(e instanceof PTE);
        hoursPerWeekLabel.setVisible(e instanceof PTE);
        hoursPerWeekField.setVisible(e instanceof PTE);
        weeksPerYearLabel.setVisible(e instanceof PTE);
        weeksPerYearField.setVisible(e instanceof PTE);
        typeField.setText(e instanceof PTE ? "Part-time" : "Full-time");
    }

    private void update() {
        if (employee == null) {
            ((CardLayout) panel1.getLayout()).show(panel1, "Placeholder");
        } else {
            var e = employee;
            ((CardLayout) panel1.getLayout()).show(panel1, "Details");
            employeeName.setText(String.format("%s %s", e.getFirstName(), e.getLastName()));
            employeeNumber.setText(String.format("#%d", e.getEmpNum()));
            fNameField.setText(e.getFirstName());
            lNameField.setText(e.getLastName());
            genderField.setText(EmployeeInfo.GENDERS[e.getGender()]);
            workLocationField.setText(Constants.WORK_LOCATIONS[e.getWorkLoc()]);
            deductionRateField.setText(Constants.PERCENTAGE_FORMAT.format(e.getDeductRate() * 100d));
            grossIncomeField.setText(Constants.MONEY_FORMAT.format(e.calcGrossAnnualIncome()));
            netIncomeField.setText(Constants.MONEY_FORMAT.format(e.calcNetAnnualIncome()));
            updateVisibility();
            if (e instanceof FTE) {
                var fte = (FTE) e;
                salaryField.setVisible(true);
                salaryField.setText(Constants.MONEY_FORMAT.format(fte.getYearlySalary()));
            } else if (e instanceof PTE) {
                var pte = (PTE) e;
                hourlyWageField.setText(Constants.MONEY_FORMAT.format(pte.getHourlyWage()));
                hoursPerWeekField.setText(Constants.DECIMAL_FORMAT.format(pte.getHoursPerWeek()));
                weeksPerYearField.setText(Constants.DECIMAL_FORMAT.format(pte.getWeeksPerYear()));
            }
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new CardLayout(0, 0));
        placeholderLabel = new JLabel();
        placeholderLabel.setHorizontalAlignment(0);
        placeholderLabel.setHorizontalTextPosition(11);
        placeholderLabel.setText("<html><p style=\"text-align: center\">Select an employee to view or edit details</p></html>");
        panel1.add(placeholderLabel, "Placeholder");
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, "Details");
        final JSeparator separator1 = new JSeparator();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(separator1, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel2.add(panel3, gbc);
        panel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, -1, panel3.getFont()), null));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, -1, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("First Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 10, 0);
        panel3.add(label1, gbc);
        fNameField = new JLabel();
        fNameField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 0, 10, 0);
        panel3.add(fNameField, gbc);
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, -1, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Last Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel3.add(label2, gbc);
        lNameField = new JLabel();
        lNameField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel3.add(lNameField, gbc);
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.BOLD, -1, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setText("Type");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 5, 0);
        panel3.add(label3, gbc);
        typeField = new JLabel();
        typeField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 5, 0);
        panel3.add(typeField, gbc);
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.BOLD, -1, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setText("Gender");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel3.add(label4, gbc);
        genderField = new JLabel();
        genderField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel3.add(genderField, gbc);
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$(null, Font.BOLD, -1, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setText("Work Location");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel3.add(label5, gbc);
        workLocationField = new JLabel();
        workLocationField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel3.add(workLocationField, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer1, gbc);
        editButton = new JButton();
        editButton.setIcon(new ImageIcon(getClass().getResource("/owenwang/ems/document-edit.png")));
        editButton.setText("Edit");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 10, 5, 5);
        panel2.add(editButton, gbc);
        removeButton = new JButton();
        removeButton.setIcon(new ImageIcon(getClass().getResource("/owenwang/ems/edit-delete.png")));
        removeButton.setText("Remove");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 10);
        panel2.add(removeButton, gbc);
        final JSeparator separator2 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(separator2, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(panel4, gbc);
        employeeName = new JLabel();
        Font employeeNameFont = this.$$$getFont$$$(null, Font.BOLD, 16, employeeName.getFont());
        if (employeeNameFont != null) employeeName.setFont(employeeNameFont);
        employeeName.setIcon(new ImageIcon(getClass().getResource("/owenwang/ems/im-user.png")));
        employeeName.setText("fName lName");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 5, 10);
        panel4.add(employeeName, gbc);
        employeeNumber = new JLabel();
        Font employeeNumberFont = this.$$$getFont$$$(null, -1, 14, employeeNumber.getFont());
        if (employeeNumberFont != null) employeeNumber.setFont(employeeNumberFont);
        employeeNumber.setText("#123456");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.SOUTHEAST;
        gbc.insets = new Insets(10, 10, 5, 10);
        panel4.add(employeeNumber, gbc);
        final JSeparator separator3 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(separator3, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 10, 0, 10);
        panel2.add(panel5, gbc);
        salaryLabel = new JLabel();
        Font salaryLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, salaryLabel.getFont());
        if (salaryLabelFont != null) salaryLabel.setFont(salaryLabelFont);
        salaryLabel.setText("Salary");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 10, 0);
        panel5.add(salaryLabel, gbc);
        salaryField = new JLabel();
        salaryField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 0, 10, 0);
        panel5.add(salaryField, gbc);
        deductionRateField = new JLabel();
        deductionRateField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(deductionRateField, gbc);
        final JLabel label6 = new JLabel();
        Font label6Font = this.$$$getFont$$$(null, Font.BOLD, -1, label6.getFont());
        if (label6Font != null) label6.setFont(label6Font);
        label6.setText("Deduction Rate");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(label6, gbc);
        hourlyWageLabel = new JLabel();
        Font hourlyWageLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, hourlyWageLabel.getFont());
        if (hourlyWageLabelFont != null) hourlyWageLabel.setFont(hourlyWageLabelFont);
        hourlyWageLabel.setText("Hourly Wage");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(hourlyWageLabel, gbc);
        hourlyWageField = new JLabel();
        hourlyWageField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(hourlyWageField, gbc);
        hoursPerWeekLabel = new JLabel();
        Font hoursPerWeekLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, hoursPerWeekLabel.getFont());
        if (hoursPerWeekLabelFont != null) hoursPerWeekLabel.setFont(hoursPerWeekLabelFont);
        hoursPerWeekLabel.setText("Hours per Week");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(hoursPerWeekLabel, gbc);
        hoursPerWeekField = new JLabel();
        hoursPerWeekField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(hoursPerWeekField, gbc);
        weeksPerYearLabel = new JLabel();
        Font weeksPerYearLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, weeksPerYearLabel.getFont());
        if (weeksPerYearLabelFont != null) weeksPerYearLabel.setFont(weeksPerYearLabelFont);
        weeksPerYearLabel.setText("Weeks Per Year");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(weeksPerYearLabel, gbc);
        weeksPerYearField = new JLabel();
        weeksPerYearField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(weeksPerYearField, gbc);
        grossIncomeField = new JLabel();
        grossIncomeField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(grossIncomeField, gbc);
        final JLabel label7 = new JLabel();
        Font label7Font = this.$$$getFont$$$(null, Font.BOLD, -1, label7.getFont());
        if (label7Font != null) label7.setFont(label7Font);
        label7.setText("Gross Income");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(label7, gbc);
        netIncomeField = new JLabel();
        netIncomeField.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(netIncomeField, gbc);
        final JLabel label8 = new JLabel();
        Font label8Font = this.$$$getFont$$$(null, Font.BOLD, -1, label8.getFont());
        if (label8Font != null) label8.setFont(label8Font);
        label8.setText("Net Income");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 10, 0);
        panel5.add(label8, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
